name: Vocative Consulting
favicon: null
layout_spectrum: 0.7880691275931895
typography_spectrum: 0.8353946523275226
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d2b09f'
    - '#92654c'
    - '#6b391b'
    - '#275076'
  brandStrength: 0.8125
  lightness: 0.875
  saturation: 0.875
  rhythmicContrast: 1
purpose: []
